name: Build IA PreÃ§o TÃ¡ Certo ?

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verificacao:
    name: Testar Ambiente e DependÃªncias
    runs-on: ubuntu-latest

    steps:
    - name: CÃ³digo Fonte ğŸ“¥
      uses: actions/checkout@v4

    - name: Configurar Python 3.10 ğŸ
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar DependÃªncias do Sistema (Cairo) ğŸ–¼ï¸
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev pkg-config

    - name: Instalar Bibliotecas do Python ğŸ“¦
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: VerificaÃ§Ã£o de Sintaxe (Lint) ğŸ”
      run: |
        pip install flake8
        # Para o build se houver erros de Python ou nomes nÃ£o definidos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
